# Travis CI build pipeline
# --------------------------------------------

os: linux
dist: xenial
language: csharp
solution: LibraryManagement.sln
mono: none
dotnet: 6.0.301

addons:
  apt:
    packages:
      - zip
      - tar
      - gzip

before_script:
  - set -e
  - dotnet restore

script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      set -e
      dotnet build -c Release
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" /p:excludebyfile="**/*.Designer.cs"
      bash <(curl -s https://codecov.io/bash) -Z
    fi

before_deploy:
  - set -e
  - dotnet build LibraryManagement.sln -c Release
  - |
    mkdir output
    mv ./Forms/bin/Release ./output/
  - |
    zip -r ./Forms.zip ./output/* 
    zip -r ./Template.zip ./Template/*
    tar cfvz ./Forms.tar.gz ./output
    tar cfvz ./Template.tar.gz ./Template

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - "./Forms.zip"
    - "./Template.zip"
    - "./Forms.tar.gz"
    - "./Template.tar.gz"
  skip_cleanup: true
  on:
    tags: true